### PR TITLE
New Extension - Swap In Out 

### PR DESCRIPTION
**Pull request by talvasconcelos**
This extension works with the etleneum.com Chainmarket contract and allows to send LN to onchain and vice versa. 

Swap Out let's you take satoshis from an LNbits wallet to an onchain address.
Swap In allows for funding an LNbits wallet with an onchain transaction.

### CODE REVIEW

**Comment by arcbtc** [comment]
Congrats. Looking forward to testing

**Comment by callebtc** [comment]
This is going to be really useful for a BTC-to-fiat extension 🌮

**Comment by arcbtc** [comment]
Oooo, fresh commits, will test now

**Comment by arcbtc** [comment]
What happens if two people pay on onchain address at the same time

**Comment by talvasconcelos** [comment]
The etleneum contract prevents that! When you click reserve, on the swap
in, the offers are no longer available for other users!
Check the contract here: https://etleneum.com/#/contract/c8w0c13v75

**Comment by arcbtc** [comment]
It doesnt. Two people could send funds at the same time

**Comment by dni** [comment]
etleneum shut down today :(

https://twitter.com/etleneum2/status/1550109786250760192

**Comment by callebtc** [comment]
Sad end for this PR. Botlz soon though!

**Pull request closed without merging**
