### PR TITLE
return lnurl in create link

### PR DESCRIPTION
**Pull request by talvasconcelos**
fix issue #680 and #681

### CODE REVIEW

**Comment by talvasconcelos** [comment]
Hi, thank you for your input. Can you please be a bit more specific on where it's breaking?

**Comment by callebtc** [comment]
@bezysoftware do you really rely on this field being empty (which is a bug)?

**Comment by bezysoftware** [comment]
Apologies I misread the PR, I wrongly assumed it would change the response object, instead of populating a missing field. Please ignore my previous comment

**Comment by talvasconcelos** [comment]
what's it breaking?!

**Pull request merged**
