### PR TITLE
SCRUB extension

### PR DESCRIPTION
**Pull request by talvasconcelos**
SCRUB® extension (we're minting the term!)

Turns an LNbits wallet as a passthrough to an LNURLpay or LNaddress!

### CODE REVIEW

**Comment by arcbtc** [comment]
image
Getting an error

**Comment by arcbtc** [comment]
Cant get funds to scrub from wallet

**Comment by talvasconcelos** [comment]
> 

your listener isn't working! it doesn't trigger whatever happens in tasks.py

**Comment by talvasconcelos** [comment]
ahh damn you, @callebtc !!! 

now his tests are forcing me to add scrub to conv.py...

**Comment by callebtc** [comment]
> ahh damn you, @callebtc !!!
> 
> now his tests are forcing me to add scrub to conv.py...

That sounds great! Hah, gotcha!

Btw, it would amazing if you could also add a sample extension db file to `tests/data/mock_data.zip` which is used for the migration test!

**Comment by callebtc** [comment]
> Getting an error

This Exception should be fixed in main now, please rebase!

**Pull request merged**
