### PR TITLE
Delete expired invoices after one pending check

### PR DESCRIPTION
**Pull request by callebtc**
PR fixes two bugs:

* Check for expired invoices regularly, instead of only upon startup.
* Expired invoices should only be deleted after one pending check. The backend could have been offline for a very long time and expired invoices could have been paid in the mean time.

### CODE REVIEW

**Comment by fiatjaf** [comment]
I like the bug fix, but I don't think we should call this regularly. It's a very intensive operation. It fetches all the invoices from the database, parses their bolt11 string and checks the expiration time for each.

**Comment by arcbtc** [comment]
Could we add another `loop.create_task`for it and run every 24hrs? That way it will run on startup as well

**Comment by callebtc** [comment]
Missed the comments, sorry. @fiatjaf what do you think of increasing the interval to 24 hours like @arcbtc said?

**Comment by callebtc** [comment]
Changed it to a one-time expiry check after the first pending check.

**Pull request merged**
