### PR TITLE
Fix minor bug

### PR DESCRIPTION
**Pull request by talvasconcelos**

### CODE REVIEW

**Comment by arcbtc** [comment]
Can you fix the conflicts

**Comment by talvasconcelos** [comment]
@arcbtc fixed

**Comment by jpentland** [comment]
I'm a bit confused. I am seeing some of these commits already merged, but the "fix minor bug" commit is currently missing from the 'main' branch.

I just submitted another PR to fix this before seeing this: https://github.com/lnbits/lnbits-legend/pull/516

**Comment by callebtc** [comment]
Duplicate of #516. Closing.

**Pull request closed without merging**
