### PR TITLE
Postman regression test - initial

### PR DESCRIPTION
**Pull request by cryptoteun**
In this initial version of the regression test the following endpoint/extensions will be included:
- [x] wallet
- [x] usermanager
- [x] LNURLp
- [x] LNURLw

Action/config included to run daily at https://lnbits.com

### CODE REVIEW

**Comment by cryptoteun** [comment]
@arcbtc this is the first running version of the postman test. I'm planning to add LNURLw short term, that's why this one is ready for review yet.

**Comment by cryptoteun** [comment]
Added LNURLw, first version ready for use.

@arcbtc
- Please let me know if you have any question. 
- I think the environment.json should contain secrets so the testdata can't be messed up by users. 
- Any suggestions on what to add next based on usage of extension?

**Comment by cryptoteun** [comment]
Test covers now:
- wallet
- usermanager
- LNURLp
- LNURLw
- Paywall
- Captcha

**Comment by cryptoteun** [comment]
Added a webhook check.

**Comment by cryptoteun** [comment]
@arcbtc , I think the test is stable now. Running against my own instance for 14 days with no problems. 

Did you already look into it?

**Comment by callebtc** [comment]
@cryptoteun hey, it's been a while since the last messages. Is this PR still relevant? I'm cleaning up a bit.

**Comment by cryptoteun** [comment]
@callebtc , it was created before the move to fastapi. Currently don't have time to check if it's still completely working. Is there still a need for such a test, which could run during build/deploy?

**Comment by callebtc** [comment]
@cryptoteun see #566 for the new test pipeline with FastApi! :)

**Pull request closed without merging**
