### PR TITLE
LndRestWallet fix: add fees to output

### PR DESCRIPTION
**Pull request by callebtc**
Only lines 113 and 115 are changes, the rest is the formatter.

### CODE REVIEW

**Comment by fusion44** [comment]
LGTM - thanks!

Tiny nitpick: I would be not commit the formatting changes as they make it a bit harder to digest the real changes.

**Comment by callebtc** [comment]
> Tiny nitpick: I would be not commit the formatting changes as they make it a bit harder to digest the real changes.

Yes, for sure, I'm using black, but my line length is maybe not the same as your's. What's the convention?

**Comment by fusion44** [comment]
Not sure, I think they are black defaults. Maybe @arcbtc can elaborate?

In cases like this I usually only stage the ranges I actually want to commit.

**Comment by callebtc** [comment]
Black default is 88 characters, I've been using 120 and it seems that you're using even more than that :)

**Comment by callebtc** [comment]
Who does the merges?

**Review by fusion44 — APPROVED** [review]
LGTM!

**Pull request merged**
