### PR TITLE
Fix lnurlpayout extension

### PR DESCRIPTION
**Pull request by leesalminen**
I cleaned up the `lnurlpayout` extension and ran a handful of test payments through it. Seems to be working now. Would love to get someone else's eyes on this branch to see if they can break it.

### CODE REVIEW

**Comment by callebtc** [comment]
Please run `black` on the repo once :) 

I haven't tested it yet, do we have an issue for this PR?

**Comment by leesalminen** [comment]
> Please run `black` on the repo once :)

Done, sorry about that!

> I haven't tested it yet, do we have an issue for this PR?

I don't see any open issue at the moment. I had a brief chat with Ben on Telegram yesterday about this. The extension was disabled in the repo, and the commit history seems to have some back and forth trying to fix things. When I enabled the extension and tried to use it, I hit some errors and exceptions. So, I just worked through them until it worked. Then did ~10 test transactions w/ payouts. It seems to be working for me. Ben wasn't sure what the problem used to be. If anyone remembers what the specific issue was last time, I'd be happy to keep digging!

**Comment by callebtc** [comment]
Hi @leesalminen, you're on fire! Can you rebase this to main and run `make format` once please?

**Comment by arcbtc** [comment]
Updated and ran format, although black does not seem to be working, would really like to get this extensions merged

**Pull request closed without merging**
