### PR TITLE
Added maxfee parameter to Spark pay method 

### PR DESCRIPTION
**Pull request by mrbitcoiner**
Working on c-lightning 0.11.0.1

Fixing the issue #640

### CODE REVIEW

**Comment by callebtc** [comment]
Thanks! 

LGTM

**Comment by callebtc** [comment]
According to https://readthedocs.org/projects/lightning/downloads/pdf/master/  from CLN 0.11.0.1 on`maxfee` can be used instead of `maxfeepercent`. Maybe we can use the same for `clightningwallet` as well. 

@mrbitcoiner I assume you have tested it? Do you think we should use `maxfeepercent` for backends that haven't upgraded to the newest version?

**Comment by mrbitcoiner** [comment]
> According to https://readthedocs.org/projects/lightning/downloads/pdf/master/ from CLN 0.11.0.1 on`maxfee` can be used instead of `maxfeepercent`. Maybe we can use the same for `clightningwallet` as well.
> 
> @mrbitcoiner I assume you have tested it? Do you think we should use `maxfeepercent` for backends that haven't upgraded to the newest version?

I've tested, running on my c-lightning v0.11.0.1 instance through spark and `maxfee` is working fine.

**Comment by callebtc** [comment]
Merging.

**Pull request merged**
